// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type AppLogReqest struct {
	Current          int64  `json:"current,default=1,optional"`     // 页码
	PageSize         int64  `json:"page_size,default=10,optional"`  // 数据量
	CreatedStartTime int64  `json:"created_start_time,optional"`    // 创建开始时间
	CreatedEndTime   int64  `json:"created_end_time,optional"`      // 创建结束时间
	Uid              string `json:"uid,optional"`                   // 用户Uid
	Ip               string `json:"ip,optional"`                    // 请求IP
	InterfaceType    string `json:"interface_type,optional"`        // 请求类型
	InterfaceAddress string `json:"interface_address,optional"`     // 请求路由
	IsRequest        int64  `json:"is_request,default=99,optional"` // 请求结果
}

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}
