// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: authentication.proto

package authentication

import (
	"context"

	"Scheduler_go/service/manage/authentication/authenticationclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResp                                 = authenticationclient.CommonResp
	FindOneInterfaceByPathAndInterfaceTypeReq  = authenticationclient.FindOneInterfaceByPathAndInterfaceTypeReq
	FindOneInterfaceByPathAndInterfaceTypeResp = authenticationclient.FindOneInterfaceByPathAndInterfaceTypeResp
	SysAuthAddReq                              = authenticationclient.SysAuthAddReq
	SysAuthDeleteReq                           = authenticationclient.SysAuthDeleteReq
	SysAuthFindOneReq                          = authenticationclient.SysAuthFindOneReq
	SysAuthFindOneResp                         = authenticationclient.SysAuthFindOneResp
	SysAuthListData                            = authenticationclient.SysAuthListData
	SysAuthListReq                             = authenticationclient.SysAuthListReq
	SysAuthListResp                            = authenticationclient.SysAuthListResp
	SysAuthUpdateReq                           = authenticationclient.SysAuthUpdateReq
	SysDictAddReq                              = authenticationclient.SysDictAddReq
	SysDictDeleteReq                           = authenticationclient.SysDictDeleteReq
	SysDictFindOneReq                          = authenticationclient.SysDictFindOneReq
	SysDictFindOneResp                         = authenticationclient.SysDictFindOneResp
	SysDictListData                            = authenticationclient.SysDictListData
	SysDictListReq                             = authenticationclient.SysDictListReq
	SysDictListResp                            = authenticationclient.SysDictListResp
	SysDictTypeAddReq                          = authenticationclient.SysDictTypeAddReq
	SysDictTypeDeleteReq                       = authenticationclient.SysDictTypeDeleteReq
	SysDictTypeFindOneReq                      = authenticationclient.SysDictTypeFindOneReq
	SysDictTypeFindOneResp                     = authenticationclient.SysDictTypeFindOneResp
	SysDictTypeListData                        = authenticationclient.SysDictTypeListData
	SysDictTypeListReq                         = authenticationclient.SysDictTypeListReq
	SysDictTypeListResp                        = authenticationclient.SysDictTypeListResp
	SysDictTypeUpdateReq                       = authenticationclient.SysDictTypeUpdateReq
	SysDictUpdateReq                           = authenticationclient.SysDictUpdateReq
	SysInterfaceAddReq                         = authenticationclient.SysInterfaceAddReq
	SysInterfaceByRoleIdReq                    = authenticationclient.SysInterfaceByRoleIdReq
	SysInterfaceByRoleIdResp                   = authenticationclient.SysInterfaceByRoleIdResp
	SysInterfaceByRoleIdRespIDsResp            = authenticationclient.SysInterfaceByRoleIdRespIDsResp
	SysInterfaceDeleteReq                      = authenticationclient.SysInterfaceDeleteReq
	SysInterfaceFindOneReq                     = authenticationclient.SysInterfaceFindOneReq
	SysInterfaceFindOneResp                    = authenticationclient.SysInterfaceFindOneResp
	SysInterfaceListData                       = authenticationclient.SysInterfaceListData
	SysInterfaceListReq                        = authenticationclient.SysInterfaceListReq
	SysInterfaceListResp                       = authenticationclient.SysInterfaceListResp
	SysInterfaceUpdateReq                      = authenticationclient.SysInterfaceUpdateReq
	SysLoginReq                                = authenticationclient.SysLoginReq
	SysMenuAddReq                              = authenticationclient.SysMenuAddReq
	SysMenuByRoleIdReq                         = authenticationclient.SysMenuByRoleIdReq
	SysMenuByRoleIdResp                        = authenticationclient.SysMenuByRoleIdResp
	SysMenuDeleteReq                           = authenticationclient.SysMenuDeleteReq
	SysMenuFindOneReq                          = authenticationclient.SysMenuFindOneReq
	SysMenuFindOneResp                         = authenticationclient.SysMenuFindOneResp
	SysMenuListData                            = authenticationclient.SysMenuListData
	SysMenuListReq                             = authenticationclient.SysMenuListReq
	SysMenuListResp                            = authenticationclient.SysMenuListResp
	SysMenuUpdateReq                           = authenticationclient.SysMenuUpdateReq
	SysRoleAddReq                              = authenticationclient.SysRoleAddReq
	SysRoleDeleteReq                           = authenticationclient.SysRoleDeleteReq
	SysRoleFindOneReq                          = authenticationclient.SysRoleFindOneReq
	SysRoleFindOneResp                         = authenticationclient.SysRoleFindOneResp
	SysRoleListData                            = authenticationclient.SysRoleListData
	SysRoleListReq                             = authenticationclient.SysRoleListReq
	SysRoleListResp                            = authenticationclient.SysRoleListResp
	SysRoleUpdateReq                           = authenticationclient.SysRoleUpdateReq
	SysUserAddReq                              = authenticationclient.SysUserAddReq
	SysUserDeleteReq                           = authenticationclient.SysUserDeleteReq
	SysUserFindOneReq                          = authenticationclient.SysUserFindOneReq
	SysUserFindOneResp                         = authenticationclient.SysUserFindOneResp
	SysUserListData                            = authenticationclient.SysUserListData
	SysUserListReq                             = authenticationclient.SysUserListReq
	SysUserListResp                            = authenticationclient.SysUserListResp
	SysUserResetPwdReq                         = authenticationclient.SysUserResetPwdReq
	SysUserResetPwdResp                        = authenticationclient.SysUserResetPwdResp
	SysUserUpMyPwdReq                          = authenticationclient.SysUserUpMyPwdReq
	SysUserUpdateReq                           = authenticationclient.SysUserUpdateReq

	Authentication interface {
		// 用户登录
		SysLogin(ctx context.Context, in *SysLoginReq, opts ...grpc.CallOption) (*SysUserFindOneResp, error)
		// 用户
		SysUserAdd(ctx context.Context, in *SysUserAddReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysUserDelete(ctx context.Context, in *SysUserDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysUserUpdate(ctx context.Context, in *SysUserUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysUserFindOne(ctx context.Context, in *SysUserFindOneReq, opts ...grpc.CallOption) (*SysUserFindOneResp, error)
		SysUserList(ctx context.Context, in *SysUserListReq, opts ...grpc.CallOption) (*SysUserListResp, error)
		// 重置用户密码
		SysUserResetPwd(ctx context.Context, in *SysUserResetPwdReq, opts ...grpc.CallOption) (*SysUserResetPwdResp, error)
		// 用户修改自己的密码
		SysUserUpMyPwd(ctx context.Context, in *SysUserUpMyPwdReq, opts ...grpc.CallOption) (*CommonResp, error)
		// 第三方用户
		SysAuthAdd(ctx context.Context, in *SysAuthAddReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysAuthDelete(ctx context.Context, in *SysAuthDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysAuthUpdate(ctx context.Context, in *SysAuthUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysAuthFindOne(ctx context.Context, in *SysAuthFindOneReq, opts ...grpc.CallOption) (*SysAuthFindOneResp, error)
		SysAuthList(ctx context.Context, in *SysAuthListReq, opts ...grpc.CallOption) (*SysAuthListResp, error)
		// 角色
		SysRoleAdd(ctx context.Context, in *SysRoleAddReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysRoleDelete(ctx context.Context, in *SysRoleDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysRoleUpdate(ctx context.Context, in *SysRoleUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysRoleFindOne(ctx context.Context, in *SysRoleFindOneReq, opts ...grpc.CallOption) (*SysRoleFindOneResp, error)
		SysRoleList(ctx context.Context, in *SysRoleListReq, opts ...grpc.CallOption) (*SysRoleListResp, error)
		// 菜单
		SysMenuAdd(ctx context.Context, in *SysMenuAddReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysMenuDelete(ctx context.Context, in *SysMenuDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysMenuUpdate(ctx context.Context, in *SysMenuUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysMenuFindOne(ctx context.Context, in *SysMenuFindOneReq, opts ...grpc.CallOption) (*SysMenuFindOneResp, error)
		SysMenuList(ctx context.Context, in *SysMenuListReq, opts ...grpc.CallOption) (*SysMenuListResp, error)
		// 通过角色ID获取菜单信息
		SysMenuByRoleId(ctx context.Context, in *SysMenuByRoleIdReq, opts ...grpc.CallOption) (*SysMenuByRoleIdResp, error)
		// 接口
		SysInterfaceAdd(ctx context.Context, in *SysInterfaceAddReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysInterfaceDelete(ctx context.Context, in *SysInterfaceDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysInterfaceUpdate(ctx context.Context, in *SysInterfaceUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysInterfaceFindOne(ctx context.Context, in *SysInterfaceFindOneReq, opts ...grpc.CallOption) (*SysInterfaceFindOneResp, error)
		SysInterfaceList(ctx context.Context, in *SysInterfaceListReq, opts ...grpc.CallOption) (*SysInterfaceListResp, error)
		// 根据请求路径/请求类型 查询
		FindOneInterfaceByPathAndInterfaceType(ctx context.Context, in *FindOneInterfaceByPathAndInterfaceTypeReq, opts ...grpc.CallOption) (*FindOneInterfaceByPathAndInterfaceTypeResp, error)
		// 通过角色ID获取接口信息
		SysInterfaceByRoleId(ctx context.Context, in *SysInterfaceByRoleIdReq, opts ...grpc.CallOption) (*SysInterfaceByRoleIdResp, error)
		// 通过角色ID获取接口IDS
		SysInterfaceByRoleIdRespIDs(ctx context.Context, in *SysInterfaceByRoleIdReq, opts ...grpc.CallOption) (*SysInterfaceByRoleIdRespIDsResp, error)
		// 字典类型
		SysDictTypeAdd(ctx context.Context, in *SysDictTypeAddReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysDictTypeDelete(ctx context.Context, in *SysDictTypeDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysDictTypeUpdate(ctx context.Context, in *SysDictTypeUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysDictTypeFindOne(ctx context.Context, in *SysDictTypeFindOneReq, opts ...grpc.CallOption) (*SysDictTypeFindOneResp, error)
		SysDictTypeList(ctx context.Context, in *SysDictTypeListReq, opts ...grpc.CallOption) (*SysDictTypeListResp, error)
		// 字典
		SysDictAdd(ctx context.Context, in *SysDictAddReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysDictDelete(ctx context.Context, in *SysDictDeleteReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysDictUpdate(ctx context.Context, in *SysDictUpdateReq, opts ...grpc.CallOption) (*CommonResp, error)
		SysDictFindOne(ctx context.Context, in *SysDictFindOneReq, opts ...grpc.CallOption) (*SysDictFindOneResp, error)
		SysDictList(ctx context.Context, in *SysDictListReq, opts ...grpc.CallOption) (*SysDictListResp, error)
	}

	defaultAuthentication struct {
		cli zrpc.Client
	}
)

func NewAuthentication(cli zrpc.Client) Authentication {
	return &defaultAuthentication{
		cli: cli,
	}
}

// 用户登录
func (m *defaultAuthentication) SysLogin(ctx context.Context, in *SysLoginReq, opts ...grpc.CallOption) (*SysUserFindOneResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysLogin(ctx, in, opts...)
}

// 用户
func (m *defaultAuthentication) SysUserAdd(ctx context.Context, in *SysUserAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysUserAdd(ctx, in, opts...)
}

func (m *defaultAuthentication) SysUserDelete(ctx context.Context, in *SysUserDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysUserDelete(ctx, in, opts...)
}

func (m *defaultAuthentication) SysUserUpdate(ctx context.Context, in *SysUserUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysUserUpdate(ctx, in, opts...)
}

func (m *defaultAuthentication) SysUserFindOne(ctx context.Context, in *SysUserFindOneReq, opts ...grpc.CallOption) (*SysUserFindOneResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysUserFindOne(ctx, in, opts...)
}

func (m *defaultAuthentication) SysUserList(ctx context.Context, in *SysUserListReq, opts ...grpc.CallOption) (*SysUserListResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysUserList(ctx, in, opts...)
}

// 重置用户密码
func (m *defaultAuthentication) SysUserResetPwd(ctx context.Context, in *SysUserResetPwdReq, opts ...grpc.CallOption) (*SysUserResetPwdResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysUserResetPwd(ctx, in, opts...)
}

// 用户修改自己的密码
func (m *defaultAuthentication) SysUserUpMyPwd(ctx context.Context, in *SysUserUpMyPwdReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysUserUpMyPwd(ctx, in, opts...)
}

// 第三方用户
func (m *defaultAuthentication) SysAuthAdd(ctx context.Context, in *SysAuthAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysAuthAdd(ctx, in, opts...)
}

func (m *defaultAuthentication) SysAuthDelete(ctx context.Context, in *SysAuthDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysAuthDelete(ctx, in, opts...)
}

func (m *defaultAuthentication) SysAuthUpdate(ctx context.Context, in *SysAuthUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysAuthUpdate(ctx, in, opts...)
}

func (m *defaultAuthentication) SysAuthFindOne(ctx context.Context, in *SysAuthFindOneReq, opts ...grpc.CallOption) (*SysAuthFindOneResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysAuthFindOne(ctx, in, opts...)
}

func (m *defaultAuthentication) SysAuthList(ctx context.Context, in *SysAuthListReq, opts ...grpc.CallOption) (*SysAuthListResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysAuthList(ctx, in, opts...)
}

// 角色
func (m *defaultAuthentication) SysRoleAdd(ctx context.Context, in *SysRoleAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysRoleAdd(ctx, in, opts...)
}

func (m *defaultAuthentication) SysRoleDelete(ctx context.Context, in *SysRoleDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysRoleDelete(ctx, in, opts...)
}

func (m *defaultAuthentication) SysRoleUpdate(ctx context.Context, in *SysRoleUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysRoleUpdate(ctx, in, opts...)
}

func (m *defaultAuthentication) SysRoleFindOne(ctx context.Context, in *SysRoleFindOneReq, opts ...grpc.CallOption) (*SysRoleFindOneResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysRoleFindOne(ctx, in, opts...)
}

func (m *defaultAuthentication) SysRoleList(ctx context.Context, in *SysRoleListReq, opts ...grpc.CallOption) (*SysRoleListResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysRoleList(ctx, in, opts...)
}

// 菜单
func (m *defaultAuthentication) SysMenuAdd(ctx context.Context, in *SysMenuAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysMenuAdd(ctx, in, opts...)
}

func (m *defaultAuthentication) SysMenuDelete(ctx context.Context, in *SysMenuDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysMenuDelete(ctx, in, opts...)
}

func (m *defaultAuthentication) SysMenuUpdate(ctx context.Context, in *SysMenuUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysMenuUpdate(ctx, in, opts...)
}

func (m *defaultAuthentication) SysMenuFindOne(ctx context.Context, in *SysMenuFindOneReq, opts ...grpc.CallOption) (*SysMenuFindOneResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysMenuFindOne(ctx, in, opts...)
}

func (m *defaultAuthentication) SysMenuList(ctx context.Context, in *SysMenuListReq, opts ...grpc.CallOption) (*SysMenuListResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysMenuList(ctx, in, opts...)
}

// 通过角色ID获取菜单信息
func (m *defaultAuthentication) SysMenuByRoleId(ctx context.Context, in *SysMenuByRoleIdReq, opts ...grpc.CallOption) (*SysMenuByRoleIdResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysMenuByRoleId(ctx, in, opts...)
}

// 接口
func (m *defaultAuthentication) SysInterfaceAdd(ctx context.Context, in *SysInterfaceAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysInterfaceAdd(ctx, in, opts...)
}

func (m *defaultAuthentication) SysInterfaceDelete(ctx context.Context, in *SysInterfaceDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysInterfaceDelete(ctx, in, opts...)
}

func (m *defaultAuthentication) SysInterfaceUpdate(ctx context.Context, in *SysInterfaceUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysInterfaceUpdate(ctx, in, opts...)
}

func (m *defaultAuthentication) SysInterfaceFindOne(ctx context.Context, in *SysInterfaceFindOneReq, opts ...grpc.CallOption) (*SysInterfaceFindOneResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysInterfaceFindOne(ctx, in, opts...)
}

func (m *defaultAuthentication) SysInterfaceList(ctx context.Context, in *SysInterfaceListReq, opts ...grpc.CallOption) (*SysInterfaceListResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysInterfaceList(ctx, in, opts...)
}

// 根据请求路径/请求类型 查询
func (m *defaultAuthentication) FindOneInterfaceByPathAndInterfaceType(ctx context.Context, in *FindOneInterfaceByPathAndInterfaceTypeReq, opts ...grpc.CallOption) (*FindOneInterfaceByPathAndInterfaceTypeResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.FindOneInterfaceByPathAndInterfaceType(ctx, in, opts...)
}

// 通过角色ID获取接口信息
func (m *defaultAuthentication) SysInterfaceByRoleId(ctx context.Context, in *SysInterfaceByRoleIdReq, opts ...grpc.CallOption) (*SysInterfaceByRoleIdResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysInterfaceByRoleId(ctx, in, opts...)
}

// 通过角色ID获取接口IDS
func (m *defaultAuthentication) SysInterfaceByRoleIdRespIDs(ctx context.Context, in *SysInterfaceByRoleIdReq, opts ...grpc.CallOption) (*SysInterfaceByRoleIdRespIDsResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysInterfaceByRoleIdRespIDs(ctx, in, opts...)
}

// 字典类型
func (m *defaultAuthentication) SysDictTypeAdd(ctx context.Context, in *SysDictTypeAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysDictTypeAdd(ctx, in, opts...)
}

func (m *defaultAuthentication) SysDictTypeDelete(ctx context.Context, in *SysDictTypeDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysDictTypeDelete(ctx, in, opts...)
}

func (m *defaultAuthentication) SysDictTypeUpdate(ctx context.Context, in *SysDictTypeUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysDictTypeUpdate(ctx, in, opts...)
}

func (m *defaultAuthentication) SysDictTypeFindOne(ctx context.Context, in *SysDictTypeFindOneReq, opts ...grpc.CallOption) (*SysDictTypeFindOneResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysDictTypeFindOne(ctx, in, opts...)
}

func (m *defaultAuthentication) SysDictTypeList(ctx context.Context, in *SysDictTypeListReq, opts ...grpc.CallOption) (*SysDictTypeListResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysDictTypeList(ctx, in, opts...)
}

// 字典
func (m *defaultAuthentication) SysDictAdd(ctx context.Context, in *SysDictAddReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysDictAdd(ctx, in, opts...)
}

func (m *defaultAuthentication) SysDictDelete(ctx context.Context, in *SysDictDeleteReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysDictDelete(ctx, in, opts...)
}

func (m *defaultAuthentication) SysDictUpdate(ctx context.Context, in *SysDictUpdateReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysDictUpdate(ctx, in, opts...)
}

func (m *defaultAuthentication) SysDictFindOne(ctx context.Context, in *SysDictFindOneReq, opts ...grpc.CallOption) (*SysDictFindOneResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysDictFindOne(ctx, in, opts...)
}

func (m *defaultAuthentication) SysDictList(ctx context.Context, in *SysDictListReq, opts ...grpc.CallOption) (*SysDictListResp, error) {
	client := authenticationclient.NewAuthenticationClient(m.cli.Conn())
	return client.SysDictList(ctx, in, opts...)
}
