// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/Masterminds/squirrel"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysUserRoleFieldNames          = builder.RawFieldNames(&SysUserRole{})
	sysUserRoleRows                = strings.Join(sysUserRoleFieldNames, ",")
	sysUserRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(sysUserRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`update_at`", "`update_time`"), ",")
	sysUserRoleRowsWithPlaceHolder = strings.Join(stringx.Remove(sysUserRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`update_at`", "`update_time`"), "=?,") + "=?"

	cacheSysUserRoleIdPrefix         = "cache:sysUserRole:id:"
	cacheSysUserRoleIdByUserIdPrefix = "cache:sysUserRole:userid:usertype:"
)

type (
	sysUserRoleModel interface {
		Insert(ctx context.Context, data *SysUserRole) (sql.Result, error)
		TransInsert(ctx context.Context, session sqlx.Session, data *SysUserRole) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysUserRole, error)
		FindByUserIdAndUserType(ctx context.Context, userId string, userType int64) (*SysUserRole, error)
		Update(ctx context.Context, data *SysUserRole) error
		Delete(ctx context.Context, id int64) error
		TransDelete(ctx context.Context, session sqlx.Session, data *SysUserRole) error
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error)
		FindList(ctx context.Context, rowBuilder squirrel.SelectBuilder, current, pageSize int64) ([]*SysUserRole, error)
		RowBuilder() squirrel.SelectBuilder
		CountBuilder(field string) squirrel.SelectBuilder
		SumBuilder(field string) squirrel.SelectBuilder
		TransCtx(ctx context.Context, fn func(ctx context.Context, sqlx sqlx.Session) error) error
	}

	defaultSysUserRoleModel struct {
		sqlc.CachedConn
		table string
	}

	SysUserRole struct {
		Id          int64         `db:"id"`           // ID
		UserId      string        `db:"user_id"`      // 用户ID
		RoleId      int64         `db:"role_id"`      // 角色ID
		UserType    sql.NullInt64 `db:"user_type"`    // 用户类型 1:普通用户 2:第三方用户
		CreatedName string        `db:"created_name"` // 创建人
		CreatedAt   time.Time     `db:"created_at"`   // 创建时间
	}
)

func newSysUserRoleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSysUserRoleModel {
	return &defaultSysUserRoleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sys_user_role`",
	}
}

func (m *defaultSysUserRoleModel) Delete(ctx context.Context, id int64) error {
	sysUserRoleIdKey := fmt.Sprintf("%s%v", cacheSysUserRoleIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, sysUserRoleIdKey)
	return err
}

func (m *defaultSysUserRoleModel) TransDelete(ctx context.Context, session sqlx.Session, data *SysUserRole) error {
	sysUserRoleIdKey := fmt.Sprintf("%s%v", cacheSysUserRoleIdPrefix, data.Id)
	sysUserRoleIdByUserIdKey := fmt.Sprintf("%s%v:%v", cacheSysUserRoleIdByUserIdPrefix, data.Id, data.UserType)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return session.ExecCtx(ctx, query, data.Id)
	}, sysUserRoleIdKey, sysUserRoleIdByUserIdKey)
	return err
}

func (m *defaultSysUserRoleModel) FindOne(ctx context.Context, id int64) (*SysUserRole, error) {
	sysUserRoleIdKey := fmt.Sprintf("%s%v", cacheSysUserRoleIdPrefix, id)
	var resp SysUserRole
	err := m.QueryRowCtx(ctx, &resp, sysUserRoleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysUserRoleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, sqlx.ErrNotFound
	default:
		return nil, err
	}

}

func (m *defaultSysUserRoleModel) FindByUserIdAndUserType(ctx context.Context, userId string, userType int64) (*SysUserRole, error) {
	sysUserRoleIdByUserIdKey := fmt.Sprintf("%s%v:%v", cacheSysUserRoleIdByUserIdPrefix, userId, userType)
	var resp SysUserRole
	err := m.QueryRowCtx(ctx, &resp, sysUserRoleIdByUserIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", sysUserRoleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, userId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, sqlx.ErrNotFound
	default:
		return nil, err
	}

}

func (m *defaultSysUserRoleModel) Insert(ctx context.Context, data *SysUserRole) (sql.Result, error) {
	sysUserRoleIdKey := fmt.Sprintf("%s%v", cacheSysUserRoleIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, sysUserRoleRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.RoleId, data.UserType, data.CreatedName, data.CreatedAt)
	}, sysUserRoleIdKey)
	return ret, err
}

func (m *defaultSysUserRoleModel) TransInsert(ctx context.Context, session sqlx.Session, data *SysUserRole) (sql.Result, error) {
	sysUserRoleIdKey := fmt.Sprintf("%s%v", cacheSysUserRoleIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, sysUserRoleRowsExpectAutoSet)
		return session.ExecCtx(ctx, query, data.UserId, data.RoleId, data.UserType, data.CreatedName, data.CreatedAt)
	}, sysUserRoleIdKey)
	return ret, err
}

func (m *defaultSysUserRoleModel) Update(ctx context.Context, data *SysUserRole) error {
	sysUserRoleIdKey := fmt.Sprintf("%s%v", cacheSysUserRoleIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysUserRoleRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.RoleId, data.UserType, data.CreatedName, data.CreatedAt, data.Id)
	}, sysUserRoleIdKey)
	return err
}

func (m *defaultSysUserRoleModel) RowBuilder() squirrel.SelectBuilder {
	return squirrel.Select(sysUserRoleRows).From(m.table)
}

func (m *defaultSysUserRoleModel) CountBuilder(field string) squirrel.SelectBuilder {
	return squirrel.Select("COUNT(" + field + ")").From(m.table)
}

func (m *defaultSysUserRoleModel) SumBuilder(field string) squirrel.SelectBuilder {
	return squirrel.Select("IFNULL(SUM(" + field + "),0)").From(m.table)
}

func (m *defaultSysUserRoleModel) FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error) {

	query, values, err := countBuilder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return 0, nil
	default:
		return 0, err
	}
}

func (m *defaultSysUserRoleModel) FindList(ctx context.Context, rowBuilder squirrel.SelectBuilder, current, pageSize int64) ([]*SysUserRole, error) {

	if current < 1 {
		current = 1
	}
	offset := (current - 1) * pageSize

	query, values, err := rowBuilder.Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*SysUserRole
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, nil
	default:
		return nil, err
	}
}

func (m *defaultSysUserRoleModel) TransCtx(ctx context.Context, fn func(ctx context.Context, sqlx sqlx.Session) error) error {
	return m.Transact(func(s sqlx.Session) error {
		return fn(ctx, s)
	})
}

func (m *defaultSysUserRoleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSysUserRoleIdPrefix, primary)
}

func (m *defaultSysUserRoleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysUserRoleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSysUserRoleModel) tableName() string {
	return m.table
}
