// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/Masterminds/squirrel"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	histProcInstVariableFieldNames          = builder.RawFieldNames(&HistProcInstVariable{})
	histProcInstVariableRows                = strings.Join(histProcInstVariableFieldNames, ",")
	histProcInstVariableRowsExpectAutoSet   = strings.Join(stringx.Remove(histProcInstVariableFieldNames, "`id`", "`create_at`", "`create_time`", "`update_at`", "`update_time`"), ",")
	histProcInstVariableRowsWithPlaceHolder = strings.Join(stringx.Remove(histProcInstVariableFieldNames, "`id`", "`create_at`", "`create_time`", "`update_at`", "`update_time`"), "=?,") + "=?"

	cacheHistProcInstVariableIdPrefix = "cache:histProcInstVariable:id:"
)

type (
	histProcInstVariableModel interface {
		Insert(ctx context.Context, data *HistProcInstVariable) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*HistProcInstVariable, error)
		Update(ctx context.Context, data *HistProcInstVariable) error
		Delete(ctx context.Context, id int64) error
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error)
		FindList(ctx context.Context, rowBuilder squirrel.SelectBuilder, current, pageSize int64) ([]*HistProcInstVariable, error)
		RowBuilder() squirrel.SelectBuilder
		CountBuilder(field string) squirrel.SelectBuilder
		SumBuilder(field string) squirrel.SelectBuilder
		TransCtx(ctx context.Context, fn func(ctx context.Context, sqlx sqlx.Session) error) error
	}

	defaultHistProcInstVariableModel struct {
		sqlc.CachedConn
		table string
	}

	HistProcInstVariable struct {
		Id          int64          `db:"id"`           // 身份ID
		ProcInstId  int64          `db:"proc_inst_id"` // 流程实例ID
		Key         string         `db:"key"`          // 变量key
		Value       string         `db:"value"`        // 变量value
		TenantId    string         `db:"tenant_id"`    // 租户ID
		Data        sql.NullString `db:"data"`
		CreatedAt   time.Time      `db:"created_at"`   // 创建时间
		UpdatedAt   sql.NullTime   `db:"updated_at"`   // 更新时间
		DeletedAt   sql.NullTime   `db:"deleted_at"`   // 删除时间
		CreatedName string         `db:"created_name"` // 创建人
		UpdatedName sql.NullString `db:"updated_name"` // 更新人
		DeletedName sql.NullString `db:"deleted_name"` // 删除人
	}
)

func newHistProcInstVariableModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultHistProcInstVariableModel {
	return &defaultHistProcInstVariableModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`hist_proc_inst_variable`",
	}
}

func (m *defaultHistProcInstVariableModel) Delete(ctx context.Context, id int64) error {
	histProcInstVariableIdKey := fmt.Sprintf("%s%v", cacheHistProcInstVariableIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, histProcInstVariableIdKey)
	return err
}

func (m *defaultHistProcInstVariableModel) FindOne(ctx context.Context, id int64) (*HistProcInstVariable, error) {
	histProcInstVariableIdKey := fmt.Sprintf("%s%v", cacheHistProcInstVariableIdPrefix, id)
	var resp HistProcInstVariable
	err := m.QueryRowCtx(ctx, &resp, histProcInstVariableIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", histProcInstVariableRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, sqlx.ErrNotFound
	default:
		return nil, err
	}

}

func (m *defaultHistProcInstVariableModel) Insert(ctx context.Context, data *HistProcInstVariable) (sql.Result, error) {
	histProcInstVariableIdKey := fmt.Sprintf("%s%v", cacheHistProcInstVariableIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, histProcInstVariableRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ProcInstId, data.Key, data.Value, data.TenantId, data.Data, data.CreatedAt, data.UpdatedAt, data.DeletedAt, data.CreatedName, data.UpdatedName, data.DeletedName)
	}, histProcInstVariableIdKey)
	return ret, err
}

func (m *defaultHistProcInstVariableModel) Update(ctx context.Context, data *HistProcInstVariable) error {
	histProcInstVariableIdKey := fmt.Sprintf("%s%v", cacheHistProcInstVariableIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, histProcInstVariableRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ProcInstId, data.Key, data.Value, data.TenantId, data.Data, data.CreatedAt, data.UpdatedAt, data.DeletedAt, data.CreatedName, data.UpdatedName, data.DeletedName, data.Id)
	}, histProcInstVariableIdKey)
	return err
}

func (m *defaultHistProcInstVariableModel) RowBuilder() squirrel.SelectBuilder {
	return squirrel.Select(histProcInstVariableRows).From(m.table)
}

func (m *defaultHistProcInstVariableModel) CountBuilder(field string) squirrel.SelectBuilder {
	return squirrel.Select("COUNT(" + field + ")").From(m.table)
}

func (m *defaultHistProcInstVariableModel) SumBuilder(field string) squirrel.SelectBuilder {
	return squirrel.Select("IFNULL(SUM(" + field + "),0)").From(m.table)
}

func (m *defaultHistProcInstVariableModel) FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error) {

	query, values, err := countBuilder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return 0, nil
	default:
		return 0, err
	}
}

func (m *defaultHistProcInstVariableModel) FindList(ctx context.Context, rowBuilder squirrel.SelectBuilder, current, pageSize int64) ([]*HistProcInstVariable, error) {

	if current < 1 {
		current = 1
	}
	offset := (current - 1) * pageSize

	query, values, err := rowBuilder.Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*HistProcInstVariable
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, nil
	default:
		return nil, err
	}
}

func (m *defaultHistProcInstVariableModel) TransCtx(ctx context.Context, fn func(ctx context.Context, sqlx sqlx.Session) error) error {
	return m.Transact(func(s sqlx.Session) error {
		return fn(ctx, s)
	})
}

func (m *defaultHistProcInstVariableModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheHistProcInstVariableIdPrefix, primary)
}

func (m *defaultHistProcInstVariableModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", histProcInstVariableRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultHistProcInstVariableModel) tableName() string {
	return m.table
}
