// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/Masterminds/squirrel"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	procInstFieldNames          = builder.RawFieldNames(&ProcInst{})
	procInstRows                = strings.Join(procInstFieldNames, ",")
	procInstRowsExpectAutoSet   = strings.Join(stringx.Remove(procInstFieldNames, "`id`", "`create_at`", "`create_time`", "`update_at`", "`update_time`"), ",")
	procInstRowsWithPlaceHolder = strings.Join(stringx.Remove(procInstFieldNames, "`id`", "`create_at`", "`create_time`", "`update_at`", "`update_time`"), "=?,") + "=?"

	cacheProcInstIdPrefix = "cache:procInst:id:"
)

type (
	procInstModel interface {
		Insert(ctx context.Context, data *ProcInst) (sql.Result, error)
		TransInsert(ctx context.Context,  session sqlx.Session,data *ProcInst) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ProcInst, error)
		Update(ctx context.Context, data *ProcInst) error
		TransUpdate(ctx context.Context, session sqlx.Session,data *ProcInst) error
		Delete(ctx context.Context, id int64) error
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error)
		FindList(ctx context.Context, rowBuilder squirrel.SelectBuilder, current, pageSize int64) ([]*ProcInst, error)
		RowBuilder() squirrel.SelectBuilder
		CountBuilder(field string) squirrel.SelectBuilder
		SumBuilder(field string) squirrel.SelectBuilder
		TransCtx(ctx context.Context, fn func(ctx context.Context, sqlx sqlx.Session) error) error
	}

	defaultProcInstModel struct {
		sqlc.CachedConn
		table string
	}

	ProcInst struct {
		Id            int64          `db:"id"`              // 流程实例ID
		ProcId        int64          `db:"proc_id"`         // 流程ID
		ProcName      string         `db:"proc_name"`       // 流程名称
		ProcVersion   int64          `db:"proc_version"`    // 流程版本号
		BusinessId    string         `db:"business_id"`     // 业务ID
		Starter       string         `db:"starter"`         // 流程发起人用户ID
		CurrentNodeId string         `db:"current_node_id"` // 当前进行节点ID
		VariablesJson sql.NullString `db:"variables_json"`  // 变量(Json)
		Status        int64          `db:"status"`          // 状态 0 未完成（审批中） 1 已完成 2 撤销
		TenantId      string         `db:"tenant_id"`       // 租户ID
		Data          sql.NullString `db:"data"`
		CreatedAt     time.Time      `db:"created_at"`   // 创建时间
		UpdatedAt     sql.NullTime   `db:"updated_at"`   // 更新时间
		DeletedAt     sql.NullTime   `db:"deleted_at"`   // 删除时间
		CreatedName   string         `db:"created_name"` // 创建人
		UpdatedName   sql.NullString `db:"updated_name"` // 更新人
		DeletedName   sql.NullString `db:"deleted_name"` // 删除人
	}
)

func newProcInstModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultProcInstModel {
	return &defaultProcInstModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`proc_inst`",
	}
}

func (m *defaultProcInstModel) Delete(ctx context.Context, id int64) error {
	procInstIdKey := fmt.Sprintf("%s%v", cacheProcInstIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, procInstIdKey)
	return err
}

func (m *defaultProcInstModel) FindOne(ctx context.Context, id int64) (*ProcInst, error) {
	procInstIdKey := fmt.Sprintf("%s%v", cacheProcInstIdPrefix, id)
	var resp ProcInst
	err := m.QueryRowCtx(ctx, &resp, procInstIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", procInstRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, sqlx.ErrNotFound
	default:
		return nil, err
	}

}

func (m *defaultProcInstModel) Insert(ctx context.Context, data *ProcInst) (sql.Result, error) {
	procInstIdKey := fmt.Sprintf("%s%v", cacheProcInstIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, procInstRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ProcId, data.ProcName, data.ProcVersion, data.BusinessId, data.Starter, data.CurrentNodeId, data.VariablesJson, data.Status, data.TenantId, data.Data, data.CreatedAt, data.UpdatedAt, data.DeletedAt, data.CreatedName, data.UpdatedName, data.DeletedName)
	}, procInstIdKey)
	return ret, err
}

func (m *defaultProcInstModel) TransInsert(ctx context.Context,  session sqlx.Session,data *ProcInst) (sql.Result, error) {
	procInstIdKey := fmt.Sprintf("%s%v", cacheProcInstIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, procInstRowsExpectAutoSet)
		return session.ExecCtx(ctx, query, data.ProcId, data.ProcName, data.ProcVersion, data.BusinessId, data.Starter, data.CurrentNodeId, data.VariablesJson, data.Status, data.TenantId, data.Data, data.CreatedAt, data.UpdatedAt, data.DeletedAt, data.CreatedName, data.UpdatedName, data.DeletedName)
	}, procInstIdKey)
	return ret, err
}

func (m *defaultProcInstModel) Update(ctx context.Context, data *ProcInst) error {
	procInstIdKey := fmt.Sprintf("%s%v", cacheProcInstIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, procInstRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ProcId, data.ProcName, data.ProcVersion, data.BusinessId, data.Starter, data.CurrentNodeId, data.VariablesJson, data.Status, data.TenantId, data.Data, data.CreatedAt, data.UpdatedAt, data.DeletedAt, data.CreatedName, data.UpdatedName, data.DeletedName, data.Id)
	}, procInstIdKey)
	return err
}


func (m *defaultProcInstModel) TransUpdate(ctx context.Context, session sqlx.Session,data *ProcInst) error {
	procInstIdKey := fmt.Sprintf("%s%v", cacheProcInstIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, procInstRowsWithPlaceHolder)
		return session.ExecCtx(ctx, query, data.ProcId, data.ProcName, data.ProcVersion, data.BusinessId, data.Starter, data.CurrentNodeId, data.VariablesJson, data.Status, data.TenantId, data.Data, data.CreatedAt, data.UpdatedAt, data.DeletedAt, data.CreatedName, data.UpdatedName, data.DeletedName, data.Id)
	}, procInstIdKey)
	return err
}
func (m *defaultProcInstModel) RowBuilder() squirrel.SelectBuilder {
	return squirrel.Select(procInstRows).From(m.table)
}

func (m *defaultProcInstModel) CountBuilder(field string) squirrel.SelectBuilder {
	return squirrel.Select("COUNT(" + field + ")").From(m.table)
}

func (m *defaultProcInstModel) SumBuilder(field string) squirrel.SelectBuilder {
	return squirrel.Select("IFNULL(SUM(" + field + "),0)").From(m.table)
}

func (m *defaultProcInstModel) FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error) {

	query, values, err := countBuilder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return 0, nil
	default:
		return 0, err
	}
}

func (m *defaultProcInstModel) FindList(ctx context.Context, rowBuilder squirrel.SelectBuilder, current, pageSize int64) ([]*ProcInst, error) {

	if current < 1 {
		current = 1
	}
	offset := (current - 1) * pageSize

	query, values, err := rowBuilder.Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ProcInst
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, nil
	default:
		return nil, err
	}
}

func (m *defaultProcInstModel) TransCtx(ctx context.Context, fn func(ctx context.Context, sqlx sqlx.Session) error) error {
	return m.Transact(func(s sqlx.Session) error {
		return fn(ctx, s)
	})
}

func (m *defaultProcInstModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheProcInstIdPrefix, primary)
}

func (m *defaultProcInstModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", procInstRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultProcInstModel) tableName() string {
	return m.table
}
