// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/Masterminds/squirrel"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	teamTypeFieldNames          = builder.RawFieldNames(&TeamType{})
	teamTypeRows                = strings.Join(teamTypeFieldNames, ",")
	teamTypeRowsExpectAutoSet   = strings.Join(stringx.Remove(teamTypeFieldNames, "`create_at`", "`create_time`", "`update_at`", "`update_time`"), ",")
	teamTypeRowsWithPlaceHolder = strings.Join(stringx.Remove(teamTypeFieldNames, "`id`", "`create_at`", "`create_time`", "`update_at`", "`update_time`"), "=?,") + "=?"

	cacheTeamTypeIdPrefix = "cache:teamType:id:"
)

type (
	teamTypeModel interface {
		Insert(ctx context.Context, data *TeamType) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*TeamType, error)
		Update(ctx context.Context, data *TeamType) error
		Delete(ctx context.Context, id string) error
		TransDelete(ctx context.Context, session sqlx.Session, id string) error
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error)
		FindList(ctx context.Context, rowBuilder squirrel.SelectBuilder, current, pageSize int64) ([]*TeamType, error)
		RowBuilder() squirrel.SelectBuilder
		CountBuilder(field string) squirrel.SelectBuilder
		SumBuilder(field string) squirrel.SelectBuilder
		TransCtx(ctx context.Context, fn func(ctx context.Context, sqlx sqlx.Session) error) error

	}

	defaultTeamTypeModel struct {
		sqlc.CachedConn
		table string
	}

	TeamType struct {
		Id          string         `db:"id"`           // 部门类型ID
		CreatedAt   time.Time      `db:"created_at"`   // 创建时间
		UpdatedAt   sql.NullTime   `db:"updated_at"`   // 更新时间
		CreatedName string         `db:"created_name"` // 创建人
		UpdatedName sql.NullString `db:"updated_name"` // 更新人
		Name        string         `db:"name"`         // 部门名称
		Description string         `db:"description"`  // 描述
		TenantId    string         `db:"tenant_id"`    // 租户ID
	}
)

func newTeamTypeModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTeamTypeModel {
	return &defaultTeamTypeModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`team_type`",
	}
}

func (m *defaultTeamTypeModel) Delete(ctx context.Context, id string) error {
	teamTypeIdKey := fmt.Sprintf("%s%v", cacheTeamTypeIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, teamTypeIdKey)
	return err
}

func (m *defaultTeamTypeModel) TransDelete(ctx context.Context, session sqlx.Session, id string) error {

	twyTeamTypeIdKey := fmt.Sprintf("%s%v", cacheTeamTypeIdPrefix, id)
	_, err := m.Exec(func(conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return session.ExecCtx(ctx, query, id)
	}, twyTeamTypeIdKey)
	return err
}

func (m *defaultTeamTypeModel) FindOne(ctx context.Context, id string) (*TeamType, error) {
	teamTypeIdKey := fmt.Sprintf("%s%v", cacheTeamTypeIdPrefix, id)
	var resp TeamType
	err := m.QueryRowCtx(ctx, &resp, teamTypeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", teamTypeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, sqlx.ErrNotFound
	default:
		return nil, err
	}

}

func (m *defaultTeamTypeModel) Insert(ctx context.Context, data *TeamType) (sql.Result, error) {
	teamTypeIdKey := fmt.Sprintf("%s%v", cacheTeamTypeIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, teamTypeRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.CreatedAt, data.UpdatedAt, data.CreatedName, data.UpdatedName, data.Name, data.Description, data.TenantId)
	}, teamTypeIdKey)
	return ret, err
}

func (m *defaultTeamTypeModel) Update(ctx context.Context, data *TeamType) error {
	teamTypeIdKey := fmt.Sprintf("%s%v", cacheTeamTypeIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, teamTypeRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CreatedAt, data.UpdatedAt, data.CreatedName, data.UpdatedName, data.Name, data.Description, data.TenantId, data.Id)
	}, teamTypeIdKey)
	return err
}

func (m *defaultTeamTypeModel) RowBuilder() squirrel.SelectBuilder {
	return squirrel.Select(teamTypeRows).From(m.table)
}

func (m *defaultTeamTypeModel) CountBuilder(field string) squirrel.SelectBuilder {
	return squirrel.Select("COUNT(" + field + ")").From(m.table)
}

func (m *defaultTeamTypeModel) SumBuilder(field string) squirrel.SelectBuilder {
	return squirrel.Select("IFNULL(SUM(" + field + "),0)").From(m.table)
}

func (m *defaultTeamTypeModel) FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder) (int64, error) {

	query, values, err := countBuilder.ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return 0, nil
	default:
		return 0, err
	}
}

func (m *defaultTeamTypeModel) FindList(ctx context.Context, rowBuilder squirrel.SelectBuilder, current, pageSize int64) ([]*TeamType, error) {

	if current < 1 {
		current = 1
	}
	offset := (current - 1) * pageSize

	query, values, err := rowBuilder.Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*TeamType
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, nil
	default:
		return nil, err
	}
}

func (m *defaultTeamTypeModel) TransCtx(ctx context.Context, fn func(ctx context.Context, sqlx sqlx.Session) error) error {
	return m.Transact(func(s sqlx.Session) error {
		return fn(ctx, s)
	})
}

func (m *defaultTeamTypeModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTeamTypeIdPrefix, primary)
}

func (m *defaultTeamTypeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", teamTypeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTeamTypeModel) tableName() string {
	return m.table
}

